FROM alpine:latest
ENV CATALINA_HOME /usr/local/tomcat
RUN apk update && apk add openjdk8 curl && rm -rf /var/cache/apk/*


# Set environment variables
ENV TOMCAT_VERSION 9.0.56

# Download and extract Apache Tomcat
RUN wget https://archive.apache.org/dist/tomcat/tomcat-9/v${TOMCAT_VERSION}/bin/apache-tomcat-${TOMCAT_VERSION}.tar.gz -O /tmp/tomcat.tar.gz \
    && mkdir -p ${CATALINA_HOME} \
    && tar xf /tmp/tomcat.tar.gz --strip-components=1 -C ${CATALINA_HOME} \
    && rm /tmp/tomcat.tar.gz

COPY tomcat-users.xml ${CATALINA_HOME}/conf/tomcat-users.xml
COPY context.xml ${CATALINA_HOME}/webapps/manager/META-INF/context.xml
COPY context.xml ${CATALINA_HOME}/webapps/host-manager/META-INF/context.xml
RUN  mkdir /usr/local/tomcat/webapps/html-files
COPY index.html /usr/local/tomcat/webapps/html-files/
COPY index.css /usr/local/tomcat/webapps/html-files/
COPY media/ /usr/local/tomcat/webapps/html-files/


EXPOSE 8080
CMD ["sh", "-c", "${CATALINA_HOME}/bin/catalina.sh run"]
